# Generated by Django 5.2.4 on 2025-07-19 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_labor', models.CharField(max_length=100)),
                ('forma_medicion', models.CharField(choices=[('día', 'Por día'), ('hectarea', 'Por hectárea'), ('metro', 'Por metro'), ('unidad', 'Por unidad')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fincas.lote')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.trabajador')),
            ],
        ),
    ]
