# Generated by Django 5.2.4 on 2025-07-25 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('forma_medicion', models.CharField(choices=[('día', 'Por día'), ('hectarea', 'Por hectárea'), ('metro', 'Por metro'), ('unidad', 'Por unidad')], max_length=20)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='labor',
            name='forma_medicion',
        ),
        migrations.RemoveField(
            model_name='labor',
            name='tipo_labor',
        ),
        migrations.AddField(
            model_name='labor',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labor',
            name='tarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='labores.tarea'),
            preserve_default=False,
        ),
    ]
