# Generated by Django 5.2.4 on 2025-07-26 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labores', '0002_tarea_remove_labor_forma_medicion_and_more'),
        ('nomina', '0002_remove_registrolaboral_parcela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='nomina_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores', to='nomina.nomina'),
        ),
    ]
