# Generated by Django 5.2.4 on 2025-07-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0001_initial'),
        ('labores', '0003_labor_nomina_asociada'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='finca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fincas.finca'),
        ),
    ]
